language: r
r: bioc-release
cache: packages

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libgsl0-dev

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'