# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

whichChar <- function(x, q) {
    .Call('motifTools_whichChar', PACKAGE = 'motifTools', x, q)
}

#' @export
alignc <- function(x, y, score_matrix, gap_score = -1L) {
    .Call('motifTools_alignc', PACKAGE = 'motifTools', x, y, score_matrix, gap_score)
}

#' @export
foo <- function() {
    .Call('motifTools_foo', PACKAGE = 'motifTools')
}

